name: books
port: 30001
deployment:
  replicas: 3

public:
  - path: "/ping"
    method: "GET"
    id: "GET_PING"

  - path: "/health"
    method: "GET"
    id: "GET_HEALTH"

  - path: "/api/book/[a-z]*[^/]+$"
    method: "POST"
    id: "GET_BOOK"
    prefix: "~ ^"

  - path: "/api/book"
    method: "POST"
    id: "GET_BOOKS"
